"""Migração inicial PostgreSQL

Revision ID: a0575c4faf07
Revises: 
Create Date: 2026-09-24 14:28:02.390653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0575c4faf07'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compartilhamentos',
    sa.Column('share_token', sa.String(length=36), nullable=False),
    sa.Column('original_sid', sa.String(length=36), nullable=False),
    sa.Column('expires_at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('share_token')
    )
    op.create_table('jogadores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('iniciais', sa.String(length=3), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('tempo_segundos', sa.Float(), nullable=False),
    sa.Column('final_alcancado', sa.String(length=100), nullable=True),
    sa.Column('dificuldade', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jogadores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jogadores_timestamp'), ['timestamp'], unique=False)

    op.create_table('saves',
    sa.Column('sid', sa.String(length=36), nullable=False),
    sa.Column('jogador_id', sa.Integer(), nullable=True),
    sa.Column('dados', sa.Text(), nullable=False),
    sa.Column('atualizado_em', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['jogador_id'], ['jogadores.id'], ),
    sa.PrimaryKeyConstraint('sid')
    )
    with op.batch_alter_table('saves', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_saves_atualizado_em'), ['atualizado_em'], unique=False)

    op.create_table('telemetria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jogador_id', sa.Integer(), nullable=True),
    sa.Column('sid_sessao', sa.String(length=36), nullable=True),
    sa.Column('evento', sa.String(length=50), nullable=False),
    sa.Column('sala', sa.String(length=50), nullable=True),
    sa.Column('dificuldade', sa.String(length=50), nullable=True),
    sa.Column('detalhes', sa.String(length=256), nullable=True),
    sa.Column('timestamp', sa.Float(), nullable=True),
    sa.Column('hp_restante', sa.Integer(), nullable=True),
    sa.Column('luz_restante', sa.Integer(), nullable=True),
    sa.Column('nivel_barulho', sa.Integer(), nullable=True),
    sa.Column('inventario_qtd', sa.Integer(), nullable=True),
    sa.Column('bolsas', sa.Integer(), nullable=True),
    sa.Column('log_comandos', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['jogador_id'], ['jogadores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('telemetria', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_telemetria_evento'), ['evento'], unique=False)
        batch_op.create_index(batch_op.f('ix_telemetria_sala'), ['sala'], unique=False)
        batch_op.create_index(batch_op.f('ix_telemetria_sid_sessao'), ['sid_sessao'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('telemetria', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_telemetria_sid_sessao'))
        batch_op.drop_index(batch_op.f('ix_telemetria_sala'))
        batch_op.drop_index(batch_op.f('ix_telemetria_evento'))

    op.drop_table('telemetria')
    with op.batch_alter_table('saves', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_saves_atualizado_em'))

    op.drop_table('saves')
    with op.batch_alter_table('jogadores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jogadores_timestamp'))

    op.drop_table('jogadores')
    op.drop_table('compartilhamentos')
    # ### end Alembic commands ###
