"""Atualizando esquema de saves

Revision ID: d88a6a01c9c4
Revises: a0575c4faf07
Create Date: 2026-09-24 14:45:05.451155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd88a6a01c9c4'
down_revision = 'a0575c4faf07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saves', schema=None) as batch_op:
        batch_op.add_column(sa.Column('metadados', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('save_version', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('checksum', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
        batch_op.alter_column('atualizado_em',
               existing_type=sa.FLOAT(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_saves_checksum'), ['checksum'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saves', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_saves_checksum'))
        batch_op.alter_column('atualizado_em',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.drop_column('criado_em')
        batch_op.drop_column('checksum')
        batch_op.drop_column('save_version')
        batch_op.drop_column('metadados')

    # ### end Alembic commands ###
