"""Otimizando indices e integridade do schema

Revision ID: e5b926fb5c96
Revises: d88a6a01c9c4
Create Date: 2026-09-24 17:44:07.257735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5b926fb5c96'
down_revision = 'd88a6a01c9c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jogadores', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=120),
               nullable=True)
        batch_op.alter_column('final_alcancado',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('dificuldade',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_jogadores_email'), ['email'], unique=True)

    with op.batch_alter_table('saves', schema=None) as batch_op:
        batch_op.alter_column('sid',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('ix_saves_atualizado_em'))
        batch_op.create_index('ix_save_jogador_atualizado', ['jogador_id', 'atualizado_em'], unique=False)

    with op.batch_alter_table('telemetria', schema=None) as batch_op:
        batch_op.alter_column('dificuldade',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('ix_telemetria_evento'))
        batch_op.drop_index(batch_op.f('ix_telemetria_sala'))
        batch_op.create_index('ix_telemetria_evento_sala', ['evento', 'sala'], unique=False)
        batch_op.create_index('ix_telemetria_evento_timestamp', ['evento', 'timestamp'], unique=False)
        batch_op.create_index('ix_telemetria_jogador_evento', ['jogador_id', 'evento'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('telemetria', schema=None) as batch_op:
        batch_op.drop_index('ix_telemetria_jogador_evento')
        batch_op.drop_index('ix_telemetria_evento_timestamp')
        batch_op.drop_index('ix_telemetria_evento_sala')
        batch_op.create_index(batch_op.f('ix_telemetria_sala'), ['sala'], unique=False)
        batch_op.create_index(batch_op.f('ix_telemetria_evento'), ['evento'], unique=False)
        batch_op.alter_column('dificuldade',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    with op.batch_alter_table('saves', schema=None) as batch_op:
        batch_op.drop_index('ix_save_jogador_atualizado')
        batch_op.create_index(batch_op.f('ix_saves_atualizado_em'), ['atualizado_em'], unique=False)
        batch_op.alter_column('sid',
               existing_type=sa.Uuid(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)

    with op.batch_alter_table('jogadores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jogadores_email'))
        batch_op.alter_column('dificuldade',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('final_alcancado',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###
